// @deepseek-ai/dsh-research-tools — P2 research pipeline tools (public entry).
//
// Scope (batch 2): literature-search (T12) / citation-verify (T13) /
// claim-construct (T14) / ablation (T15) / figure (T16) / three-line-table
// (T17). Each tool is a PURE, fixture-driven function that returns a deeply
// frozen artifact and NEVER advances the batch-1 state machine (see shared.ts
// rule 4 + D:\1\plan\batch2-t19-hold-abstained-design.md).
//
// Ownership (main Agent): this file is the single public import surface; it
// aggregates the per-tool modules that land in their own exclusive
// directories (packages/research/dsh-research-tools/src/tools/<name> + the
// matching tests/<name>). Tool agents do not edit this file. A shared tool
// REGISTRY for the future T19 pipeline is deliberately NOT introduced in this
// wave — each artifact already self-describes via meta.toolId + meta.version,
// and the registry shape belongs to the T19 pre-contract design.
//
// Import convention: tool-internal modules import each other with '.ts'
// relative suffixes; consumers import this entry by package name
// ('@deepseek-ai/dsh-research-tools').

// ── Shared conventions (main-Agent-owned) ──────────────────────────────────
export { freezeArtifact } from './shared.ts'
export type { ToolArtifactMeta } from './shared.ts'

// ── T12 literature-search (literature-search/literature-search tool) ────────
// runLiteratureSearch(query, adapter, timestamp) + LiteratureSearchError +
// artifact/type surface; NO DEFAULT PASS ('unavailable' != empty 'ok').
export * from './tools/literature-search/index.ts'

// ── T13 citation-verify (THIN delegation over core T08 verifyCitation) ─────
// verifyCitationTool(input, deps) — validates only the non-empty branded ids,
// delegates with core's exact argument order, freezes the core result. No
// verdict logic lives in the tool.
export * from './tools/citation-verify/index.ts'

// ── T14 claim-construct (DAG step A2 claim constructor) ─────────────────────
// constructClaim(input) / runClaimConstruct — pure construction; the artifact
// claim always carries supportStatus: 'not_claimed' (never literature support).
export * from './tools/claim-construct/index.ts'

// ── T15 ablation (ablation-run definition + execution adapter + audit) ──────
// runAblation(definition, executor, timestamp) — MEASUREMENTS ONLY: records
// planned/executed/failed/partial runs and per-variant descriptive stats of
// EXECUTED runs; never emits a delta/effect/causal conclusion. Real runs
// enter ONLY through the injected executor (fixture mock in this wave).
export * from './tools/ablation/index.ts'

// ── T16 figure (SVG + real-byte PNG renderer) ───────────────────────────────
// renderFigure(spec, timestamp) — deterministic SVG string + REAL byte-valid
// PNG (built-in node:zlib + hand-rolled CRC/IHDR/IDAT/IEND; zero third-party
// runtime deps). Pure; never writes the filesystem (pathguard is exported for
// downstream stages that accept an output path).
export * from './tools/figure/index.ts'

// ── T17 three-line-table (structured model -> Markdown/LaTeX booktabs) ──────
// renderThreeLineTable(model, target, timestamp) — one structured table model,
// rendered as GitHub Markdown (exactly 3 horizontal rules) or LaTeX booktabs
// (no vertical rules anywhere). Faithful: never alters/fills/infers data.
export * from './tools/three-line-table/index.ts'
